extends Node

enum CameraFacing {
	FACING_FRONT,
	FACING_BACK,
}

enum TaskDelegate {
	DELEGATE_CPU,
	DELEGATE_GPU,
	DELEGATE_EDGETPU_NNAPI,
}

enum TaskRunningMode {
	RUNNING_MODE_AUDIO_CLIPS = 1,
	RUNNING_MODE_AUDIO_STREAM = 2,
	RUNNING_MODE_IMAGE = 1,
	RUNNINE_MODE_VIDEO = 2,
	RUNNING_MODE_LIVE_STREAM = 3,
}
