load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
load("//mediapipe/GDMP:variables.bzl", "CALCULATORS")

mediapipe_aar(
    name = "mediapipe_aar",
    calculators = CALCULATORS,
    assets = [
        # place the calculator assets here
    ]
)
