load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_aar",
    calculators = [
        # place the calculator dependencies here
    ],
    assets = [
        # place the calculator assets here
    ]
)
