cc_library(
    name = "classifier_options",
    srcs = ["classifier_options.cc"],
    hdrs = ["classifier_options.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@godot-cpp//:godot",
        "@mediapipe//mediapipe/tasks/cc/components/processors:classifier_options",
    ],
)

cc_library(
    name = "embedder_options",
    srcs = ["embedder_options.cc"],
    hdrs = ["embedder_options.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@godot-cpp//:godot",
        "@mediapipe//mediapipe/tasks/cc/components/processors:embedder_options",
    ],
)
