cc_library(
    name = "landmark",
    srcs = [
        "landmark.h",
        "macros.h",
    ],
    hdrs = ["landmark.h"],
    deps = [
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//third_party:godot",
    ],
    visibility = ["//visibility:public"],
)
