cc_library(
    name = "proto",
    srcs = [
        "proto.cc",
        "util.cc"
    ],
    hdrs = [
        "proto.h",
        "util.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:protobuf",
        "@godot-cpp//:godot",
    ],
)
