name: 🍏 Build iOS
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
  workflow_dispatch:

env:
  work-dir: ${{ github.workspace }}

jobs:
  build:
    name: iOS xcframework
    runs-on: macos-14
    steps:
      - name: Set Working Directory
        if: ${{ inputs.working-directory != '' }}
        run: echo "work-dir=${{ inputs.working-directory }}" >> $GITHUB_ENV

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          cache-save: ${{ github.event_name != 'pull_request' }}
          disk-cache: ios
          external-cache: true

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup
        working-directory: ${{ env.work-dir }}
        run: |
          python ./setup.py

      - name: Build
        working-directory: ${{ env.work-dir }}
        run: |
          python ./build.py ios --output build/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: GDMP-ios
          path: |
            ${{ env.work-dir }}/build/*.xcframework
