name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: GDMP

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          zip -r GDMP-${{ github.event.release.tag_name }}.zip addons/
          gh release upload ${{ github.event.release.tag_name }} GDMP-${{ github.event.release.tag_name }}.zip
